### ISSUE TITLE
non-ts version?

### ISSUE THREAD

**Issue by amcdnl** [mgechev/ng2lint#12]
A non-typescript version would be nice! is this on your roadmap?

**Comment by mgechev** [comment]
There's a major refactoring coming soon and we will concentrate mostly on TypeScript.

Are you using Angular 2 with ES2016?

**Comment by amcdnl** [comment]
I'm rolling stage-0 Babel.

**Comment by mgechev** [comment]
Without type annotations we won't be able to achieve the same functionality as what we're planning. Most likely non-ts version will not be implemented.

**Comment by amcdnl** [comment]
Thanks for feedback either way; cheers!
