### ISSUE TITLE
Added this repo to the TSLint docs

### ISSUE THREAD

**Issue by JKillian** [mgechev/ng2lint#2]
Hi @mgechev - just wanted to let you know that I've added your repository to the [TSLint README](https://github.com/palantir/tslint#custom-rules) and [documentation](http://palantir.github.io/tslint/usage/custom-rules/) as a place to find custom rules for TSLint. Neat idea to make a collection of Angular2 rules!

**Comment by mgechev** [comment]
Thanks!
